# Generated by Django 4.2.1 on 2023-05-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatos',
            options={'verbose_name_plural': 'Contatos'},
        ),
    ]
