# Generated by Django 4.2.1 on 2023-05-04 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contatos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='foto_url',
            field=models.URLField(default='https://www.via-placeholder.com/150'),
        ),
    ]
