/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.entidade.Usuario;

/**
 *
 * @author maken.rosa
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private Usuario user;
    private final PesquisaUsuario pesqUser;
    private final CadastroUsuario cadUser;



    /**
     * Creates new form TelaPrincipal
     * @param user
     */
    
    public TelaPrincipal(Usuario user) {
        initComponents();
        this.user = user;
        this.pesqUser = new PesquisaUsuario();
        this.cadUser = new CadastroUsuario();
        varWelcome.setText("Seja bem vindo, "+user.getNome()+ "!");
    }
    
    public TelaPrincipal() {
        initComponents();
        this.pesqUser = new PesquisaUsuario();
        this.cadUser = new CadastroUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varWelcome = new javax.swing.JLabel();
        iconeCadUser = new javax.swing.JLabel();
        iconePesqUsuario = new javax.swing.JLabel();
        varMenu = new javax.swing.JMenuBar();
        varMenuCad = new javax.swing.JMenu();
        varCadUser = new javax.swing.JMenuItem();
        varCadPerfil = new javax.swing.JMenuItem();
        varMenuPesq = new javax.swing.JMenu();
        varPesqUser = new javax.swing.JMenuItem();
        varPesqPerfil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Senac");

        varWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        iconeCadUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cadUsuario.png"))); // NOI18N
        iconeCadUser.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        iconeCadUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconeCadUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconeCadUserMouseClicked(evt);
            }
        });

        iconePesqUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pesqUsuario.png"))); // NOI18N
        iconePesqUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pesquisar", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        iconePesqUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        iconePesqUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconePesqUsuarioMouseClicked(evt);
            }
        });

        varMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        varMenuCad.setText("Cadastro");

        varCadUser.setText("Usuario");
        varCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varCadUserActionPerformed(evt);
            }
        });
        varMenuCad.add(varCadUser);

        varCadPerfil.setText("Perfil");
        varMenuCad.add(varCadPerfil);

        varMenu.add(varMenuCad);

        varMenuPesq.setText("Pesquisa");

        varPesqUser.setText("Usuario");
        varMenuPesq.add(varPesqUser);

        varPesqPerfil.setText("Perfil");
        varMenuPesq.add(varPesqPerfil);

        varMenu.add(varMenuPesq);

        setJMenuBar(varMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(430, Short.MAX_VALUE)
                .addComponent(varWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconeCadUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconePesqUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(varWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconePesqUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconeCadUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iconeCadUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconeCadUserMouseClicked
        // TODO add your handling code here:
        if (this.cadUser.isVisible() == false){
            cadUser.setVisible(true);
        } else {
            cadUser.requestFocus();
        }
    }//GEN-LAST:event_iconeCadUserMouseClicked

    private void iconePesqUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconePesqUsuarioMouseClicked
        // TODO add your handling code here:
        if (this.pesqUser.isVisible() == false){
            pesqUser.setVisible(true);
        } else {
            pesqUser.requestFocus();
        }
    }//GEN-LAST:event_iconePesqUsuarioMouseClicked

    private void varCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varCadUserActionPerformed
        // TODO add your handling code here:
        cadUser.setVisible(true);
    }//GEN-LAST:event_varCadUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconeCadUser;
    private javax.swing.JLabel iconePesqUsuario;
    private javax.swing.JMenuItem varCadPerfil;
    private javax.swing.JMenuItem varCadUser;
    private javax.swing.JMenuBar varMenu;
    private javax.swing.JMenu varMenuCad;
    private javax.swing.JMenu varMenuPesq;
    private javax.swing.JMenuItem varPesqPerfil;
    private javax.swing.JMenuItem varPesqUser;
    private javax.swing.JLabel varWelcome;
    // End of variables declaration//GEN-END:variables
}
